### ISSUE TITLE
Tidak ada entri makna pada kata khayal

### ISSUE THREAD

**Issue by noaione** [laymonage/kbbi-python#9]
https://kbbi.kemdikbud.go.id/entri/khayal

Menggunakan versi 0.3.2

```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from kbbi import KBBI
>>> KBBI('khayal')
<KBBI: khayal>
>>> test = KBBI('khayal')
>>> test
<KBBI: khayal>
>>> print(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\kbbi\kbbi.py", line 77, in __str__
    result = '\n\n'.join(str(entri) for entri in self.entri)
  File "C:\Python36\lib\site-packages\kbbi\kbbi.py", line 77, in <genexpr>
    result = '\n\n'.join(str(entri) for entri in self.entri)
  File "C:\Python36\lib\site-packages\kbbi\kbbi.py", line 212, in __str__
    return hasil + '\n' + self._makna()
  File "C:\Python36\lib\site-packages\kbbi\kbbi.py", line 171, in _makna
    return str(self.makna[0])
IndexError: list index out of range
>>> test.serialisasi()
{'khayal': [{'nama': 'kha.yal', 'nomor': '', 'kata_dasar': [], 'pelafalan': '', 'bentuk_tidak_baku': ['kayal'], 'varian': [], 'makna': []}]}
```

**Comment by laymonage** [comment]
Halo @noaione, terima kasih atas isu yang telah dibuat! :+1:

Saya rasa ini berkaitan dengan #4. Saya belum sempat memperbaikinya untuk sekarang ini. Apakah Saudara mau buat Pull Request untuk memperbaikinya?

**Comment by noaione** [comment]
Mungkin saja.
Ini sekalian lagi tak buatkan fitur autentikasi agar bisa mendapatkan etimologi dan kata turunan yang hanya tersedia bagi pengguna.

**Comment by laymonage** [comment]
Telah diperbaiki dalam #10.
